//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/KsiegarniaCDA.DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult))]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string TextField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BooksSearchSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/KsiegarniaCDA.DTO")]
    public partial class BooksSearchSearchCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> IdAutoraField;
        
        private System.Nullable<int> IdGatunkuField;
        
        private string OpisField;
        
        private System.Nullable<int> RokWydaniaField;
        
        private string TytulField;
        
        private string WydawnictwoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdAutora {
            get {
                return this.IdAutoraField;
            }
            set {
                if ((this.IdAutoraField.Equals(value) != true)) {
                    this.IdAutoraField = value;
                    this.RaisePropertyChanged("IdAutora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdGatunku {
            get {
                return this.IdGatunkuField;
            }
            set {
                if ((this.IdGatunkuField.Equals(value) != true)) {
                    this.IdGatunkuField = value;
                    this.RaisePropertyChanged("IdGatunku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RokWydania {
            get {
                return this.RokWydaniaField;
            }
            set {
                if ((this.RokWydaniaField.Equals(value) != true)) {
                    this.RokWydaniaField = value;
                    this.RaisePropertyChanged("RokWydania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tytul {
            get {
                return this.TytulField;
            }
            set {
                if ((object.ReferenceEquals(this.TytulField, value) != true)) {
                    this.TytulField = value;
                    this.RaisePropertyChanged("Tytul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wydawnictwo {
            get {
                return this.WydawnictwoField;
            }
            set {
                if ((object.ReferenceEquals(this.WydawnictwoField, value) != true)) {
                    this.WydawnictwoField = value;
                    this.RaisePropertyChanged("Wydawnictwo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BooksSearchSearchResult", Namespace="http://schemas.datacontract.org/2004/07/KsiegarniaCDA.DTO")]
    public partial class BooksSearchSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AutorField;
        
        private string GatunekField;
        
        private int IdKsiazkiField;
        
        private string RokWydaniaField;
        
        private string TytulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gatunek {
            get {
                return this.GatunekField;
            }
            set {
                if ((object.ReferenceEquals(this.GatunekField, value) != true)) {
                    this.GatunekField = value;
                    this.RaisePropertyChanged("Gatunek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiazki {
            get {
                return this.IdKsiazkiField;
            }
            set {
                if ((this.IdKsiazkiField.Equals(value) != true)) {
                    this.IdKsiazkiField = value;
                    this.RaisePropertyChanged("IdKsiazki");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RokWydania {
            get {
                return this.RokWydaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.RokWydaniaField, value) != true)) {
                    this.RokWydaniaField = value;
                    this.RaisePropertyChanged("RokWydania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tytul {
            get {
                return this.TytulField;
            }
            set {
                if ((object.ReferenceEquals(this.TytulField, value) != true)) {
                    this.TytulField = value;
                    this.RaisePropertyChanged("Tytul");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KsiegarniaCDAServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/AutorzyComboPobierz", ReplyAction="http://tempuri.org/IService/AutorzyComboPobierzResponse")]
        System.IAsyncResult BeginAutorzyComboPobierz(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> EndAutorzyComboPobierz(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GatunkiComboPobierz", ReplyAction="http://tempuri.org/IService/GatunkiComboPobierzResponse")]
        System.IAsyncResult BeginGatunkiComboPobierz(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> EndGatunkiComboPobierz(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/SearchBooks", ReplyAction="http://tempuri.org/IService/SearchBooksResponse")]
        System.IAsyncResult BeginSearchBooks(KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria searchCriteria, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult> EndSearchBooks(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutorzyComboPobierzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AutorzyComboPobierzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatunkiComboPobierzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GatunkiComboPobierzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService>, KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService {
        
        private BeginOperationDelegate onBeginAutorzyComboPobierzDelegate;
        
        private EndOperationDelegate onEndAutorzyComboPobierzDelegate;
        
        private System.Threading.SendOrPostCallback onAutorzyComboPobierzCompletedDelegate;
        
        private BeginOperationDelegate onBeginGatunkiComboPobierzDelegate;
        
        private EndOperationDelegate onEndGatunkiComboPobierzDelegate;
        
        private System.Threading.SendOrPostCallback onGatunkiComboPobierzCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchBooksDelegate;
        
        private EndOperationDelegate onEndSearchBooksDelegate;
        
        private System.Threading.SendOrPostCallback onSearchBooksCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AutorzyComboPobierzCompletedEventArgs> AutorzyComboPobierzCompleted;
        
        public event System.EventHandler<GatunkiComboPobierzCompletedEventArgs> GatunkiComboPobierzCompleted;
        
        public event System.EventHandler<SearchBooksCompletedEventArgs> SearchBooksCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService.BeginAutorzyComboPobierz(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAutorzyComboPobierz(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService.EndAutorzyComboPobierz(System.IAsyncResult result) {
            return base.Channel.EndAutorzyComboPobierz(result);
        }
        
        private System.IAsyncResult OnBeginAutorzyComboPobierz(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService)(this)).BeginAutorzyComboPobierz(callback, asyncState);
        }
        
        private object[] OnEndAutorzyComboPobierz(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> retVal = ((KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService)(this)).EndAutorzyComboPobierz(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAutorzyComboPobierzCompleted(object state) {
            if ((this.AutorzyComboPobierzCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AutorzyComboPobierzCompleted(this, new AutorzyComboPobierzCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AutorzyComboPobierzAsync() {
            this.AutorzyComboPobierzAsync(null);
        }
        
        public void AutorzyComboPobierzAsync(object userState) {
            if ((this.onBeginAutorzyComboPobierzDelegate == null)) {
                this.onBeginAutorzyComboPobierzDelegate = new BeginOperationDelegate(this.OnBeginAutorzyComboPobierz);
            }
            if ((this.onEndAutorzyComboPobierzDelegate == null)) {
                this.onEndAutorzyComboPobierzDelegate = new EndOperationDelegate(this.OnEndAutorzyComboPobierz);
            }
            if ((this.onAutorzyComboPobierzCompletedDelegate == null)) {
                this.onAutorzyComboPobierzCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAutorzyComboPobierzCompleted);
            }
            base.InvokeAsync(this.onBeginAutorzyComboPobierzDelegate, null, this.onEndAutorzyComboPobierzDelegate, this.onAutorzyComboPobierzCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService.BeginGatunkiComboPobierz(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGatunkiComboPobierz(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService.EndGatunkiComboPobierz(System.IAsyncResult result) {
            return base.Channel.EndGatunkiComboPobierz(result);
        }
        
        private System.IAsyncResult OnBeginGatunkiComboPobierz(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService)(this)).BeginGatunkiComboPobierz(callback, asyncState);
        }
        
        private object[] OnEndGatunkiComboPobierz(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> retVal = ((KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService)(this)).EndGatunkiComboPobierz(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGatunkiComboPobierzCompleted(object state) {
            if ((this.GatunkiComboPobierzCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GatunkiComboPobierzCompleted(this, new GatunkiComboPobierzCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GatunkiComboPobierzAsync() {
            this.GatunkiComboPobierzAsync(null);
        }
        
        public void GatunkiComboPobierzAsync(object userState) {
            if ((this.onBeginGatunkiComboPobierzDelegate == null)) {
                this.onBeginGatunkiComboPobierzDelegate = new BeginOperationDelegate(this.OnBeginGatunkiComboPobierz);
            }
            if ((this.onEndGatunkiComboPobierzDelegate == null)) {
                this.onEndGatunkiComboPobierzDelegate = new EndOperationDelegate(this.OnEndGatunkiComboPobierz);
            }
            if ((this.onGatunkiComboPobierzCompletedDelegate == null)) {
                this.onGatunkiComboPobierzCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGatunkiComboPobierzCompleted);
            }
            base.InvokeAsync(this.onBeginGatunkiComboPobierzDelegate, null, this.onEndGatunkiComboPobierzDelegate, this.onGatunkiComboPobierzCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService.BeginSearchBooks(KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria searchCriteria, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchBooks(searchCriteria, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult> KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService.EndSearchBooks(System.IAsyncResult result) {
            return base.Channel.EndSearchBooks(result);
        }
        
        private System.IAsyncResult OnBeginSearchBooks(object[] inValues, System.AsyncCallback callback, object asyncState) {
            KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria searchCriteria = ((KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria)(inValues[0]));
            return ((KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService)(this)).BeginSearchBooks(searchCriteria, callback, asyncState);
        }
        
        private object[] OnEndSearchBooks(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult> retVal = ((KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService)(this)).EndSearchBooks(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchBooksCompleted(object state) {
            if ((this.SearchBooksCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchBooksCompleted(this, new SearchBooksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchBooksAsync(KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria searchCriteria) {
            this.SearchBooksAsync(searchCriteria, null);
        }
        
        public void SearchBooksAsync(KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria searchCriteria, object userState) {
            if ((this.onBeginSearchBooksDelegate == null)) {
                this.onBeginSearchBooksDelegate = new BeginOperationDelegate(this.OnBeginSearchBooks);
            }
            if ((this.onEndSearchBooksDelegate == null)) {
                this.onEndSearchBooksDelegate = new EndOperationDelegate(this.OnEndSearchBooks);
            }
            if ((this.onSearchBooksCompletedDelegate == null)) {
                this.onSearchBooksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchBooksCompleted);
            }
            base.InvokeAsync(this.onBeginSearchBooksDelegate, new object[] {
                        searchCriteria}, this.onEndSearchBooksDelegate, this.onSearchBooksCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService CreateChannel() {
            return new ServiceClientChannel(this);
        }
        
        private class ServiceClientChannel : ChannelBase<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService>, KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService {
            
            public ServiceClientChannel(System.ServiceModel.ClientBase<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.IService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAutorzyComboPobierz(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("AutorzyComboPobierz", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> EndAutorzyComboPobierz(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> _result = ((System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item>)(base.EndInvoke("AutorzyComboPobierz", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGatunkiComboPobierz(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GatunkiComboPobierz", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> EndGatunkiComboPobierz(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item> _result = ((System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.Item>)(base.EndInvoke("GatunkiComboPobierz", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearchBooks(KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchCriteria searchCriteria, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = searchCriteria;
                System.IAsyncResult _result = base.BeginInvoke("SearchBooks", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult> EndSearchBooks(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult> _result = ((System.Collections.ObjectModel.ObservableCollection<KsiegarniaCDA.GUI.SL.KsiegarniaCDAServiceReference.BooksSearchSearchResult>)(base.EndInvoke("SearchBooks", _args, result)));
                return _result;
            }
        }
    }
}
