//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastKnowledgeWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Typ_firmy
    {
        public Typ_firmy()
        {
            this.Dostawca = new HashSet<Dostawca>();
        }

        [Key]
        public int id_term { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<Dostawca> Dostawca { get; set; }
    }
}
