//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastKnowledgeWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Zasoby
    {
        [Key]
        public int id_zasobu { get; set; }
        public string nazwa_zasobu { get; set; }
        public Nullable<int> id_firmy { get; set; }
    
        public virtual Dostawca Dostawca { get; set; }
    }
}
